"""add imagen column

Revision ID: c61a5337b6be
Revises: 
Create Date: 2025-06-12 22:17:44.550471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61a5337b6be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=50), nullable=False),
    sa.Column('productos', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('pago', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('hora_pago', sa.DateTime(), nullable=True),
    sa.Column('hora_preparacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('precio_grande', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('imagen', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('pedido')
    # ### end Alembic commands ###
